spring.application.name=UV_Ocean_Waves_API_Gateway_MicroService
spring.jpa.properties.hibernate.connection.release_mode=auto
#$spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.main.allow-bean-definition-overriding=true